volumes:
  pg-data:
    driver: local

networks:
  symfony-network:
    driver: bridge

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: nginx
    restart: unless-stopped
    environment:
      NGINX_HOST: localhost
    ports:
      - "80:80"
    depends_on:
      - "php-fpm"
    volumes:
      - .:/var/www/html
      - ./var/log/nginx:/var/log/nginx
      - ./docker/nginx/templates:/etc/nginx/templates
    networks:
      - symfony-network

  php-fpm:
    build:
      context: .
      dockerfile: docker/php-fpm/Dockerfile
    container_name: php-fpm
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    networks:
      - symfony-network

  composer:
    image: composer:lts
    container_name: composer
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - symfony-network
    depends_on:
      - php-fpm

  database:
    image: postgres:16.3-alpine
    container_name: database
    env_file: ./docker/.env
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data:rw
    networks:
      - symfony-network